server:
  port: 8443

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-one:8761/eureka/

spring:
  application:
    name: geteway
  rabbitmq:
    host: 192.168.113.15
    port: 5672
    virtualHost: /spring_cloud_test
    username: spring-cloud
    password: 3nodcomcn
  redis:
    host: 192.168.113.15
    port: 6379
    password: 0098a9c3caee7c545b36a521aaa7eef4@3nod
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1  #令牌桶的容积
          redis-rate-limiter.burstCapacity: 1  #流速 每秒
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@remoteAddressKeyResolver}" #SPEL表达式去的对应的bean
      routes:
      # =====================================
      - id: authorization-server
        uri: lb://authorization-server
        predicates:
        - Path=/authorization-server/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=foo, bar
      - id: producer
        uri: lb://producer
        predicates:
        - Path=/producer/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=foo, bar

gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/monitor/,/turbine/,/actuator/

management:
  endpoints:
    web:
      exposure:
        include: '*'

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#  compression:
#    response:
#      enabled: true
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB