server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-one:8761/eureka/

spring:
  application:
    name: authorization-server
  rabbitmq:
    host: 192.168.113.15
    port: 5672
    virtualHost: /spring_cloud_test
    username: spring-cloud
    password: 3nodcomcn
  redis:
    host: 192.168.113.15
    port: 6379
    password: 0098a9c3caee7c545b36a521aaa7eef4@3nod
  datasource:
    url: jdbc:postgresql://192.168.107.241:5432/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      url: http://${BOOT_ADMIN_HOST:localhost}:${BOOT_ADMIN_PORT:8022}
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  security:
    oauth2:
      jwt:
        signingKey: 123456

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    com.springboot.auth: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
